# Generated by Django 5.1.6 on 2025-03-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.BooleanField(default=False)),
                ('ham', models.BooleanField(default=False)),
            ],
        ),
    ]
